# Codecov Configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    # Project coverage must meet target
    project:
      default:
        target: 80%              # Minimum 80% coverage required
        threshold: 1%            # Allow max 1% coverage drop
        if_ci_failed: error      # Block if CI failed

    # PR changes must meet target
    patch:
      default:
        target: 80%              # New code must have 80% coverage
        threshold: 0%            # No coverage drop allowed for new code
        if_not_found: success    # Don't fail if no previous coverage

  # Precision of coverage percentage
  precision: 2
  round: down
  range: "70...100"

# Comment on PRs with coverage changes
comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false         # Comment even if no changes
  require_base: false            # Comment even on first commit
  require_head: true             # Only comment if head coverage exists

# Flags for different parts of coverage
flags:
  backend:
    paths:
      - apps/backend/src/
    carryforward: true           # Keep coverage if backend not changed

  frontend:
    paths:
      - apps/frontend/src/
    carryforward: true           # Keep coverage if frontend not changed

# Ignore files/folders
ignore:
  - "apps/backend/tests/**"
  - "apps/frontend/tests/**"
  - "apps/frontend/coverage/**"
  - "apps/backend/htmlcov/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/__pycache__/**"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/vite.config.*"
  - "**/vitest.config.*"
  - "**/cypress.config.*"
  - "deployment/**"
  - "scripts/**"
  - "tools/**"

# GitHub Checks
github_checks:
  annotations: true              # Show coverage annotations on files
