# Auto-generated script to fetch all SoundTouch API endpoint schemas
# Generated by: analyze_api.py

$ErrorActionPreference = 'SilentlyContinue'

# Device configurations
$devices = @(
    @{Name='ST30_Wohnzimmer'; IP='192.0.2.78'; ID='78'; Model='SoundTouch 30'},
    @{Name='ST10_Kueche'; IP='192.0.2.79'; ID='79'; Model='SoundTouch 10'},
    @{Name='ST300_TV'; IP='192.0.2.83'; ID='83'; Model='SoundTouch 300'}
)

# Endpoints to fetch (GET requests)
$readOnlyEndpoints = @(
    '/DSPMonoStereo',
    '/audiodspcontrols',
    '/audioproductlevelcontrols',
    '/audioproducttonecontrols',
    '/balance',
    '/bass',
    '/bassCapabilities',
    '/bluetoothInfo',
    '/bookmark',
    '/capabilities',
    '/clockTime',
    '/genreStations',
    '/getActiveWirelessProfile',
    '/getGroup',
    '/getZone',
    '/info',
    '/introspect',
    '/key',
    '/language',
    '/listMediaServers',
    '/marge',
    '/masterMsg',
    '/name',
    '/nameSource',
    '/navigate',
    '/netStats',
    '/networkInfo',
    '/notification',
    '/pdo',
    '/powerManagement',
    '/powersaving',
    '/productcechdmicontrol',
    '/producthdmiassignmentcontrols',
    '/rebroadcastlatencymode',
    '/recents',
    '/requestToken',
    '/search',
    '/searchStation',
    '/serviceAvailability',
    '/slaveMsg',
    '/soundTouchConfigurationStatus',
    '/sourceDiscoveryStatus',
    '/sources',
    '/speaker',
    '/stationInfo',
    '/supportedURLs',
    '/systemtimeout',
    '/systemtimeoutcontrol',
    '/test',
    '/trackInfo',
    '/volume'
)

Write-Host 'Fetching API schemas from all devices...' -ForegroundColor Cyan
Write-Host

foreach ($device in $devices) {
    Write-Host "Device: $($device.Model) ($($device.Name))" -ForegroundColor Yellow
    
    foreach ($endpoint in $readOnlyEndpoints) {
        $url = "http://$($device.IP):8090$endpoint"
        $filename = "device_$($device.ID)$($endpoint.Replace('/', '_')).xml"
        
        Write-Host "  Fetching: $endpoint" -NoNewline
        
        try {
            $response = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 5
            $response.Content | Out-File -Encoding UTF8 "backend\bose_api\$filename"
            Write-Host " [OK]" -ForegroundColor Green
        } catch {
            Write-Host " [SKIP]" -ForegroundColor Gray
        }
    }
    Write-Host
}

Write-Host 'Done!' -ForegroundColor Green