#!/usr/bin/env python3
"""
Analyze supported URLs across all SoundTouch devices and fetch API schemas.

Compares supportedURLs.xml from all devices and identifies model-specific endpoints.
"""
import xml.etree.ElementTree as ET
from pathlib import Path
from collections import defaultdict

# Device configurations
DEVICES = {
    "ST30_Living Room": {"ip": "192.0.2.78", "id": "78", "model": "SoundTouch 30"},
    "ST10_Kueche": {"ip": "192.0.2.79", "id": "79", "model": "SoundTouch 10"},
    "ST300_TV": {"ip": "192.0.2.83", "id": "83", "model": "SoundTouch 300"},
}


def parse_supported_urls(file_path: Path) -> set[str]:
    """Parse supportedURLs.xml and return set of endpoint URLs."""
    tree = ET.parse(file_path)
    root = tree.getroot()
    return {url.get("location") for url in root.findall("URL")}


def analyze_endpoints():
    """Analyze all devices and categorize endpoints."""
    api_dir = Path(__file__).parent

    # Parse all supported URLs
    device_endpoints = {}
    for name, config in DEVICES.items():
        file_path = api_dir / f"device_{config['id']}_supportedURLs.xml"
        device_endpoints[name] = parse_supported_urls(file_path)

    # Find common and unique endpoints
    all_endpoints = set()
    for endpoints in device_endpoints.values():
        all_endpoints.update(endpoints)

    # Common endpoints (present in ALL devices)
    common_endpoints = all_endpoints.copy()
    for endpoints in device_endpoints.values():
        common_endpoints &= endpoints

    # Categorize endpoints
    categorized = {
        "common": sorted(common_endpoints),
        "model_specific": defaultdict(list),
    }

    # Find model-specific endpoints
    for name, endpoints in device_endpoints.items():
        unique = endpoints - common_endpoints
        if unique:
            categorized["model_specific"][DEVICES[name]["model"]] = sorted(unique)

    return categorized, device_endpoints, all_endpoints


def print_analysis(categorized, device_endpoints):
    """Print endpoint analysis."""
    print("=" * 80)
    print("SOUNDTOUCH API ENDPOINT ANALYSIS")
    print("=" * 80)
    print()

    print(
        f"Total unique endpoints: {len(categorized['common']) + sum(len(eps) for eps in categorized['model_specific'].values())}"
    )
    print(f"Common endpoints (all models): {len(categorized['common'])}")
    print()

    # Device summary
    print("Device Coverage:")
    for name, endpoints in device_endpoints.items():
        model = DEVICES[name]["model"]
        print(f"  {model:20s} ({name:20s}): {len(endpoints)} endpoints")
    print()

    # Model-specific endpoints
    if categorized["model_specific"]:
        print("Model-Specific Endpoints:")
        for model, endpoints in categorized["model_specific"].items():
            print(f"\n  {model} ONLY ({len(endpoints)} endpoints):")
            for ep in endpoints:
                print(f"    {ep}")
    else:
        print("No model-specific endpoints - all devices have identical API!")
    print()


def generate_fetch_script(all_endpoints, output_file: Path):
    """Generate PowerShell script to fetch all endpoint schemas."""
    script_lines = [
        "# Auto-generated script to fetch all SoundTouch API endpoint schemas",
        "# Generated by: analyze_api.py",
        "",
        "$ErrorActionPreference = 'SilentlyContinue'",
        "",
        "# Device configurations",
        "$devices = @(",
    ]

    for name, config in DEVICES.items():
        script_lines.append(
            f"    @{{Name='{name}'; IP='{config['ip']}'; ID='{config['id']}'; Model='{config['model']}'}}"
            + ("," if name != list(DEVICES.keys())[-1] else "")
        )

    script_lines.append(")")
    script_lines.append("")
    script_lines.append("# Endpoints to fetch (GET requests)")
    script_lines.append("$readOnlyEndpoints = @(")

    # Only GET-safe endpoints (exclude write operations)
    read_only_endpoints = sorted(
        [
            ep
            for ep in all_endpoints
            if not any(
                write_word in ep.lower()
                for write_word in [
                    "set",
                    "add",
                    "remove",
                    "store",
                    "enter",
                    "clear",
                    "select",
                    "pair",
                    "cancel",
                    "update",
                    "factory",
                    "push",
                    "play",
                    "standby",
                    "abort",
                    "start",
                    "check",
                    "perform",
                    "user",
                    "critical",
                ]
            )
        ]
    )

    for i, ep in enumerate(read_only_endpoints):
        script_lines.append(
            f"    '{ep}'" + ("," if i < len(read_only_endpoints) - 1 else "")
        )

    script_lines.append(")")
    script_lines.append("")
    script_lines.append(
        "Write-Host 'Fetching API schemas from all devices...' -ForegroundColor Cyan"
    )
    script_lines.append("Write-Host")
    script_lines.append("")
    script_lines.append("foreach ($device in $devices) {")
    script_lines.append(
        '    Write-Host "Device: $($device.Model) ($($device.Name))" -ForegroundColor Yellow'
    )
    script_lines.append("    ")
    script_lines.append("    foreach ($endpoint in $readOnlyEndpoints) {")
    script_lines.append('        $url = "http://$($device.IP):8090$endpoint"')
    script_lines.append(
        "        $filename = \"device_$($device.ID)$($endpoint.Replace('/', '_')).xml\""
    )
    script_lines.append("        ")
    script_lines.append('        Write-Host "  Fetching: $endpoint" -NoNewline')
    script_lines.append("        ")
    script_lines.append("        try {")
    script_lines.append(
        "            $response = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 5"
    )
    script_lines.append(
        '            $response.Content | Out-File -Encoding UTF8 "backend\\bose_api\\$filename"'
    )
    script_lines.append('            Write-Host " [OK]" -ForegroundColor Green')
    script_lines.append("        } catch {")
    script_lines.append('            Write-Host " [SKIP]" -ForegroundColor Gray')
    script_lines.append("        }")
    script_lines.append("    }")
    script_lines.append("    Write-Host")
    script_lines.append("}")
    script_lines.append("")
    script_lines.append("Write-Host 'Done!' -ForegroundColor Green")

    output_file.write_text("\n".join(script_lines), encoding="utf-8")
    print(f"Generated fetch script: {output_file}")
    print(f"  Read-only endpoints to fetch: {len(read_only_endpoints)}")
    print(
        f"  Write endpoints skipped (safety): {len(all_endpoints) - len(read_only_endpoints)}"
    )


if __name__ == "__main__":
    # Analyze endpoints
    categorized, device_endpoints, all_endpoints = analyze_endpoints()

    # Print analysis
    print_analysis(categorized, device_endpoints)

    # Generate fetch script
    api_dir = Path(__file__).parent
    fetch_script = api_dir.parent.parent / "fetch-api-schemas.ps1"
    generate_fetch_script(all_endpoints, fetch_script)

    print()
    print("=" * 80)
    print("NEXT STEPS:")
    print("=" * 80)
    print("1. Run: .\\fetch-api-schemas.ps1")
    print("2. Review downloaded schemas in backend/bose_api/")
    print("3. Create consolidated API documentation")
